/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Adaptive_Bit_Loading.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(61094f7c79bb68f4faaef35544fcd6e2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/customModule/Adaptive_Bit_Loading.h>
// pydoc.h is automatically generated in the build directory
#include <Adaptive_Bit_Loading_pydoc.h>

void bind_Adaptive_Bit_Loading(py::module& m)
{

    using Adaptive_Bit_Loading    = gr::customModule::Adaptive_Bit_Loading;


    py::class_<Adaptive_Bit_Loading, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<Adaptive_Bit_Loading>>(m, "Adaptive_Bit_Loading", D(Adaptive_Bit_Loading))

        .def(py::init(&Adaptive_Bit_Loading::make),
           D(Adaptive_Bit_Loading,make)
        )
        



        ;




}








