/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_frame_equal_vcvc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a2c5b1f154b897f6e21199b9c0233b47)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/customModule/ofdm_frame_equal_vcvc.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_frame_equal_vcvc_pydoc.h>

void bind_ofdm_frame_equal_vcvc(py::module& m)
{

    using ofdm_frame_equal_vcvc = ::gr::customModule::ofdm_frame_equal_vcvc;


    py::class_<ofdm_frame_equal_vcvc,
               gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ofdm_frame_equal_vcvc>>(
        m, "ofdm_frame_equal_vcvc", D(ofdm_frame_equal_vcvc))

        .def(py::init(&ofdm_frame_equal_vcvc::make),
             py::arg("equalizer"),
             py::arg("cp_len"),
             py::arg("len_tag_key"),
             py::arg("propagate_channel_state"),
             py::arg("fixed_frame_len"),
             D(ofdm_frame_equal_vcvc, make))


        ;
}
