/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Permutation_Matrix.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0f0f746fdd6285d6faf56978fc39b02a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/customModule/Permutation_Matrix.h>
// pydoc.h is automatically generated in the build directory
#include <Permutation_Matrix_pydoc.h>

void bind_Permutation_Matrix(py::module& m)
{

    using Permutation_Matrix    = gr::customModule::Permutation_Matrix;


    py::class_<Permutation_Matrix, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<Permutation_Matrix>>(m, "Permutation_Matrix", D(Permutation_Matrix))

        .def(py::init(&Permutation_Matrix::make),
           D(Permutation_Matrix,make)
        )
        



        ;




}








